version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: node index.js

  test:
    build: .
    volumes:
      - .:/usr/src/app
    command: npm run test:watch
