version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: node index.js

  test:
    build: .
    volumes:
      - .:/app
    command: npm run test:watch
